name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests=false

      - uses: actions/upload-artifact@master
        with:
          name: java-jar
          path: target/

  package:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        uses: actions/download-artifact@master
        with:
          name: java-jar
          path: target/
        run:  docker build . --file k8s/docker/Dockerfile --tag trainingsground_actions:$(date +%s)
  